#! /usr/bin/env/python                                                                                                                                                                                         │
                                                                                                                                                                                                                  │
                                                                                                                                                                                                                  │
                                                                                                                                                                                                                  │
   class TimelineEventUpdateView(UpdateView):                                                                                                                                                                     │
       model = Event                                                                                                                                                                                              │
       fields = ('', '', )  # all without timeline                                                                                                                                                                │
                                                                                                                                                                                                                  │
       def get_success_url(self):                                                                                                                                                                                 │
          return reverse('timeline_timeline_detail', args=(self.object.timeline.pk,))                                                                                                                            │
                                                                                                                                                                                                                 │
                                                                                                                                                                                                                 │
  class TimelineEventCreateView(CreateView):                                                                                                                                                                     │
      model = Event                                                                                                                                                                                              │
      fields = ('', '', )  # all without timeline                                                                                                                                                                │
                                                                                                                                                                                                                 │
      def dispatch(self, request, *args, **kwargs):                                                                                                                                                              │
          self.timeline = get_object_or_404(Timeline, pk=kwargs['pk'])                                                                                                                                           │
          return super(TimelineEventCreateView, self).dispatch(request, *args, **kwargs)                                                                                                                         │
                                                                                                                                                                                                                 │
      def form_valid(self, form):                                                                                                                                                                                │
          form.instance.timeline = self.timeline                                                                                                                                                                 │
          return super(TimelineEventCreateView, self).form_valid(form)                                                                                                                                           │
                                                                                                                                                                                                                 │
      def get_success_url(self):                                                                                                                                                                                 │
          return reverse('timeline_timeline_detail', args=(self.object.timeline.pk,))                                                                                                                            │
                                                                                                                                                                                                                │
      def get_context_data(self, **kwargs):                                                                                                                                                                      │
          kwargs['timeline'] = self.timeline                                                                                                                                                                     │
          return super(TimelineEventCreateView, self).get_context_data(**kwargs)                                                                                                                                 │
                                                                                                                                                                                                                 │
  #urls.py                                                                                                                                                                                                       │
                                                                                                                                                                                                                 │
      #url(r'^timeline/timeline/(?P<pk>[\d]+)/$', timeline_views.TimelineDetailView.as_view(), name='timeline_timeline_detail'),                                                                                 │
      url(r'^timeline/timeline/(?P<pk>[\d]+)/update/$', timeline_views.TimelineUpdateView.as_view(), name='timeline_timeline_update'),                                                                           │
      url(r'^timeline/timeline/(?P<pk>[\d]+)/event/create/$', timeline_views.TimelineEventCreateView.as_view(), name='timeline_timeline_event_create'),                                                          │
      url(r'^timeline/timeline/(?P<pk>[\d]+)/event/list/$', timeline_views.TimelineEventCreateView.as_view(), name='timeline_timeline_event_create'),                                                            │
      #url(r'^timeline/timeline/event/(?P<pk>[\d]+)/$', timeline_views.TimelineEventDetailView.as_view(), name='timeline_timeline_event_detail'),                                                                │
      url(r'^timeline/timeline/event/(?P<pk>[\d]+)/update/$', timeline_views.TimelineEventUpdateView.as_view(), name='timeline_timeline_event_update'),                                                          │
                                                                                                                                                                                                                 │
                                                                                                                                                                                                                 │
      <a href="{% url 'timeline_timeline_update' timeline.pk %}">{{ timeline.title }}                                                                                                                            │
      {% for event in timeline.event_set.all %}                                                                                                                                                                  │
          <a href="{% url 'timeline_timeline_event_update' event.pk %}">{{ event.title }}</a></i></a>                                                                                                            │
      {% else %}                                                                                                                                                                                                 │
          <span>Keine</span>                                                                                                                                                                                     │
      {% endfor %}                                                                                                                                                                                               │
      <a href="{% url 'timeline_timeline_text_update' timeline.text.pk %}">{{ timeline.text.title }}</a></i></a>